### ISSUE TITLE
Remove use of rgeos

### ISSUE THREAD

**Issue by rsbivand** [Molina-Valero/FORTLS#12]
This package has strong dependence on at least one of `rgdal`, `rgeos` or `maptools`, but does not seem to use any functionality in code. The usage may have been in `raster`, which now uses `terra` instead, or may be in examples or vignettes. Please move all use of `rgdal`, `rgeos` or `maptools` to Suggests: and protect any use against these packages not being present. The packages will be archived in October 2023. See https://r-spatial.org/r/2022/12/14/evolution2.html and https://rsbivand.github.io/csds_jan23/bivand_csds_ssg_230117.pdf and perhaps view https://www.youtube.com/watch?v=TlpjIqTPMCA&list=PLzREt6r1NenmWEidssmLm-VO_YmAh4pq9&index=1.

**Comment by Molina-Valero** [comment]
Thank you very much! I will consider your suggestions.
Juan Alberto

**Comment by rsbivand** [comment]
Please also see https://r-spatial.org/r/2023/04/10/evolution3.html, fix best by June, latest October 2023.

**Comment by rsbivand** [comment]
@Molina-Valero Please also see https://r-spatial.org/r/2023/05/15/evolution4.html; less than three months remain to retain this package on CRAN. Unfortunately, no positive changes are visible in the github repository.

**Comment by Molina-Valero** [comment]
I will work on that asap. Thank you again!

**Comment by Molina-Valero** [comment]
It is done. Thank you very much!
