### ISSUE TITLE
LAS won't normalize due to Z value restrictions

### ISSUE THREAD

**Issue by ashlynolah** [Molina-Valero/FORTLS#18]
Every time I try to run my code for the normalize() function, I get errors when I add constraints for the min.height and max.height values. 

I keep getting this error: Error in `$<-.data.frame`(x, name, value): replacement has 2 rows, data has 0

It runs when I have the NULL function in, but when I try to define my own constraints, it doesn't seem to run, and I'm not sure why. It stops at 83%.

My scans are single tree scans of the base of giant sequoia adapted from iPad Pro LiDAR.  Each scan only has one tree stump in it. 

`las_317 <- readLAS("utm_zone_11_point_cloud.las")`

`pcd.single1 <- normalize(las = las_317,
                 x.center = 328275.5, y.center = 4063829, 
                 max.dist = 15, 
                 min.height = min(las_317), \
                 max.height = max(las_317), 
                 algorithm.dtm = "knnidw", res.dtm = 0.2,
                 csf = list(cloth_resolution = 0.5),
                 RGB = TRUE,
                 scan.approach = "single", file = NULL,
                 id = "utm_zone_11_point_cloud.las",
                 dir.data = dir.data, dir.result = dir.result)`

Any assistance with this would be helpful. I've tried all different kinds of numbers for the min and max height, not sure how to troubleshoot this further. The file is too big to paste here but I can email it to you if you provide your email.

**Comment by ashlynolah** [comment]
I've zipped up the LAS file and added it here: [](https://drive.google.com/drive/folders/1gI2wpXHy1F5WerbHqB3qW4hFw-Jq__mw?usp=sharing)

**Comment by ashlynolah** [comment]
Sent you an email!

**Comment by Molina-Valero** [comment]
Ok. So, we are in contact by email!
Juan
