### ISSUE TITLE
README.md links the wrong paper...

### ISSUE THREAD

**Issue by bi0m3trics** [Molina-Valero/FORTLS#4]
The link in the README.md links to a paper titled "A Review on the Nematicidal Activity of Volatile Allelochemicals against the Pinewood Nematode" by Faria et al. 2020. I'm guessing this is a mistake...  ;)

**Comment by Molina-Valero** [comment]
Hello! You are right, this is a mistake which I have solved right now. Thank you very much for your comment ;)

**Comment by cingularities** [comment]
Unfortunately, the link is still wrong!

**Comment by Molina-Valero** [comment]
Hello! I have check the link in the README.md (https://doi.org/10.3390/IECF2020-08066) and It is right. The title of the paper should be: "FORTLS: An R Package for Processing TLS Data and Estimating Stand Variables in Forest Inventories".
