### ISSUE TITLE
Error in deldir

### ISSUE THREAD

**Issue by flottsam** [Molina-Valero/FORTLS#5]
I'm trying to understand the meaning of this error message when running the `metrics.variables` function on multiple TLS scans: 
```
Error in deldir(pts@coords[, 1], pts@coords[, 2], rw = rw, suppressMsge = TRUE) : 
  There is at most one point inside the given
  rectangular window. Thus there are insufficiently
  many points to triangulate/tessellate.
```

The scan that the function fails on (scan #2 in the list of scans) does not actually contain trees. 
I assume that the function fails because no trees were detected. If this is the case, it would make more sense to have the function output NA, and keep processing the remaining scans.

**Comment by Molina-Valero** [comment]
Dear cwadeross,

I think you are using the B version of FORTLS, because you are talking about TLS multiple scans. In that case, we are updating the metrics.variables funtion. However, problems with no detected trees must appear before (in tree.detection.several.plots I guess). This means you should not have trees belonging to your scan #2 and therefore, in metrics.variables the function will jump to the scan #3 because there are not rows in the tree list belonging to #2. Another possible problem may be with the plot center coordinates...

Maybe you could pass me your data to see what happen?

Best regards,
Juan Alberto

**Comment by cwadeross** [comment]
Thank you for the quick response. 
Here's a subset of the raw scans: https://drive.google.com/drive/folders/1ndraIrCAqtYaOffpRPg6iSMhS21Y6jm6?usp=sharing
Each of these scans contains trees, but I receive the above error on plot 10 and plot 25. 

Very nice package!

**Comment by Molina-Valero** [comment]
I think they are single scans of TLS. Is that right? In that case, I will need the resolution as follow: 

tls.resolution List containing parameters of TLS resolution. This can be defined by the angle
aperture:
• horizontal.angle: horizontal angle aperture (degrees).
• vertical.angle: vertical angle aperture (degrees).
or separation between two consecutive points at a certain distance from TLS:
• point.dist: distance (mm) between two consecutive points.
• tls.dist: distance (m) from TLS at which two consecutive points are
separated by point.dist.

Best regards,
Juan Alberto

**Comment by cwadeross** [comment]
Hmm, yes single scan from a Leica BLK360. 
I'll see if I can find the spec sheet, I did not take the scans myself.

**Comment by cwadeross** [comment]
I was able to find this in the manual online. Using the high density mode, the resolution should be 5mm at 10 m distance.

**Comment by Molina-Valero** [comment]
Thank you! I will check it asap

**Comment by Molina-Valero** [comment]
I sent you an email. Please, let me know if you received it

**Comment by cwadeross** [comment]
Hello Juan,

I've been busy with field work, but have had a chance to go through the
code this morning.
I can't seem to get the metrics.variable function to find the output (.txt)
files.
I've triple-checked the file paths, and they are correct.
The dir.data and dir.result are using the same path.
The output .txt files have the same names as the scans, but I keep
receiving the error:


*Error in .sim.calc(funct = "metr", tree.list.tls = tree.list.tls,
tree.list.ds = tree.list.ds,  :   TXT file(s) 'plot_1.1.las.txt',
'plot_2.1.las.txt' in 'tree.list.tls' argument does(do) not exists in the
directory specified in 'dir.data' argument.*

Any suggestions?


 -wade

**Comment by Molina-Valero** [comment]
Hello,

Please, check that the output .txt files have the same names as the column file in the tree.list.tls data frame. They must be coincident.

Let me known if you have solved this issue.

Best,
Juan

De: cross ***@***.***>
Enviado el: lunes, 7 de febrero de 2022 17:40
Para: Molina-Valero/FORTLS ***@***.***>
CC: MOLINA VALERO JUAN ALBERTO ***@***.***>; Comment ***@***.***>
Asunto: Re: [Molina-Valero/FORTLS] Error in deldir (Issue #5)

Hello Juan,

I've been busy with field work, but have had a chance to go through the
code this morning.
I can't seem to get the metrics.variable function to find the output (.txt)
files.
I've triple-checked the file paths, and they are correct.
The dir.data and dir.result are using the same path.
The output .txt files have the same names as the scans, but I keep
receiving the error:


*Error in .sim.calc(funct = "metr", tree.list.tls = tree.list.tls,
tree.list.ds = tree.list.ds, : TXT file(s) 'plot_1.1.las.txt',
'plot_2.1.las.txt' in 'tree.list.tls' argument does(do) not exists in the
directory specified in 'dir.data' argument.*

Any suggestions?


-wade

**Comment by cwadeross** [comment]
Hey Juan,

Disregard that email, I noticed that the dir.data and dir.result arguments
were wrapped inside the plot.parameters argument.

 -wade

**Comment by cwadeross** [comment]
Thanks again for the speedy response. I was testing on a very small set and
will run this again.

 -wade

**Comment by Molina-Valero** [comment]
OK. If you install the lastest version, please run all the code from the beginning because we often update the beta version.

**Comment by cwadeross** [comment]
Will do, thanks!

 -wade
