### ISSUE TITLE
Visual tree segmentation

### ISSUE THREAD

**Issue by zzk112233** [Molina-Valero/FORTLS#7]
Hi, this is a really cool package. There are good results in tree segmentation, but how do I check the actual results of tree segmentation in points cloud？ Is there any method or code to visualize tree segmentation? Like the second image in your vignettes（https://cran.r-project.org/web/packages/FORTLS/vignettes/tree_level.html）.

I look forward to hearing from you. Thank you very much.

**Comment by Molina-Valero** [comment]
Hi! Thank you very much for your compliments.

There is not any method included in the package to visualize tree segmentation (maybe in the future). But you can generate a point cloud with the estimated diameters by FORTLS and visualize it together with the normalized point clould. I use CloudCompare for that purpose. To generate the estimated diameters you can use the next R code:

```
diameter <- data.frame(tree = as.numeric(),
                       x = as.numeric(),
                       y = as.numeric(),
                       z = as.numeric())

phi <- seq(from = 0, to = 2*pi, by = 2 * pi / 10000)

for (i in tree.tls$tree) {

  tree <- rep(i, times = 10001)
  x <- tree.tls$x[i] + cos(phi) * ((tree.tls$dbh[i] / 100) / 2)
  y <- tree.tls$y[i] + sin(phi) * ((tree.tls$dbh[i] / 100) / 2)
  z <- runif(10001, 1.2, 1.4)

  .diameter <- data.frame(tree = tree, x = x, y = y, z = z)

  diameter <- rbind(diameter, .diameter)

}

write.csv(diameter, "diameters_single.csv")
```

Where tree.tls is the data frame generated by FORTLS after detecting trees.

Best,
Juan

**Comment by zzk112233** [comment]
I am so happy to hear that, thank you so much for your time and help.Your code is working！！！！！：）

**Comment by zzk112233** [comment]
I am so happy to hear that, thank you so much for your time and help！Your code is working！！：）
